package com.medilabo.patient.controller;

import com.medilabo.patient.dto.PatientDto;
import com.medilabo.patient.mapper.PatientMapper;
import com.medilabo.patient.model.Patient;
import com.medilabo.patient.service.PatientService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * REST controller exposing CRUD operations on patients.  All endpoints are
 * versioned under the "/api" prefix to ease future versioning.
 */
@RestController
@RequestMapping("/api/patients")
@CrossOrigin(origins = "*")
public class PatientController {

    private final PatientService patientService;

    public PatientController(PatientService patientService) {
        this.patientService = patientService;
    }

    /**
     * List all patients.
     *
     * @return list of patient DTOs
     */
    @GetMapping
    public ResponseEntity<List<PatientDto>> getAllPatients() {
        List<PatientDto> dtos = patientService.findAll().stream()
                .map(PatientMapper::toDto)
                .collect(Collectors.toList());
        return ResponseEntity.ok(dtos);
    }

    /**
     * Retrieve a single patient by id.
     *
     * @param id patient identifier
     * @return the patient if found or 404 otherwise
     */
    @GetMapping("/{id}")
    public ResponseEntity<PatientDto> getPatient(@PathVariable("id") Long id) {
        Optional<Patient> patientOpt = patientService.findById(id);
        return patientOpt
                .map(p -> ResponseEntity.ok(PatientMapper.toDto(p)))
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    /**
     * Create a new patient record.  The request body must contain a valid
     * {@link PatientDto} without an id.  The id will be generated by the
     * persistence layer.
     *
     * @param dto patient data
     * @return the persisted patient DTO
     */
    @PostMapping
    public ResponseEntity<PatientDto> createPatient(@Valid @RequestBody PatientDto dto) {
        // Ensure that id is null to avoid accidentally updating an existing entity
        dto.setId(null);
        Patient saved = patientService.save(PatientMapper.toEntity(dto));
        return new ResponseEntity<>(PatientMapper.toDto(saved), HttpStatus.CREATED);
    }

    /**
     * Update an existing patient.  The id in the path is authoritative; it
     * overrides any id contained in the DTO.  If no patient with the given id
     * exists, a 404 is returned.
     *
     * @param id patient identifier to update
     * @param dto new patient data
     * @return the updated patient DTO
     */
    @PutMapping("/{id}")
    public ResponseEntity<PatientDto> updatePatient(
            @PathVariable("id") Long id,
            @Valid @RequestBody PatientDto dto) {
        Optional<Patient> existing = patientService.findById(id);
        if (existing.isEmpty()) {
            return ResponseEntity.notFound().build();
        }
        dto.setId(id);
        Patient saved = patientService.update(PatientMapper.toEntity(dto));
        return ResponseEntity.ok(PatientMapper.toDto(saved));
    }
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deletePatient(@PathVariable("id") Long id) {
        patientService.delete(id);
        return ResponseEntity.noContent().build(); // 204 No Content
    }
}